// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { brokeredPreviewStorage } from './previewAuthStorage';

const SUPABASE_URL = "https://xbbeuiciduestsvjecdt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhiYmV1aWNpZHVlc3RzdmplY2R0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODQyNzU2NTIsImV4cCI6MjA5OTg1MTY1Mn0.bUjGO4Lh1Ae8KKcM_VNA0J3tlOqdZR0IDb1zfSFHc7U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: brokeredPreviewStorage(),
    persistSession: true,
    autoRefreshToken: true,
  }
});